// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyB7ZoWbyTEsmB396UAB5pQs2uYxdw_Vo3c",
  authDomain: "neuroguard-82e63.firebaseapp.com",
  databaseURL: "https://neuroguard-82e63-default-rtdb.firebaseio.com",
  projectId: "neuroguard-82e63",
  storageBucket: "neuroguard-82e63.firebasestorage.app",
  messagingSenderId: "470690299791",
  appId: "1:470690299791:web:ef0f0b2a798a9f7e9995fa"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQ2X8Y9Z1A2B3C4D5E6F7G8H9I0J1K2L',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'neuroguard-app',
    storageBucket: 'neuroguard-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQ2X8Y9Z1A2B3C4D5E6F7G8H9I0J1K2L',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'neuroguard-app',
    storageBucket: 'neuroguard-app.appspot.com',
    iosBundleId: 'com.example.nngapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQ2X8Y9Z1A2B3C4D5E6F7G8H9I0J1K2L',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'neuroguard-app',
    storageBucket: 'neuroguard-app.appspot.com',
    iosBundleId: 'com.example.nngapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQ2X8Y9Z1A2B3C4D5E6F7G8H9I0J1K2L',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'neuroguard-app',
    authDomain: 'neuroguard-app.firebaseapp.com',
    storageBucket: 'neuroguard-app.appspot.com',
  );
}
