// This file is generated by Flutter and should not be modified manually.
// It handles service worker functionality for the web app.

'use strict';

const CACHE_NAME = 'neuroguard-app-v1';
const urlsToCache = [
  './',
  './main.dart.js',
  './flutter.js',
  './favicon.png',
  './icons/Icon-192.png',
  './icons/Icon-512.png',
  './manifest.json'
];

self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(function(cache) {
        return cache.addAll(urlsToCache);
      })
  );
});

self.addEventListener('fetch', function(event) {
  event.respondWith(
    caches.match(event.request)
      .then(function(response) {
        if (response) {
          return response;
        }
        return fetch(event.request);
      }
    )
  );
});
